#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated from flash_attn.xlsx by xlsx_to_testcase.py
# DO NOT EDIT — regenerate from source xlsx instead.
#
# Total cases: 53

TestCases = {
    'flash_atten_test_0001': {
        'B': [144],
        'N1': [16],
        'N2': [16],
        'S1': [936],
        'S2': [936],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0002': {
        'B': [128],
        'N1': [16],
        'N2': [16],
        'S1': [910],
        'S2': [910],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0003': {
        'B': [384],
        'N1': [16],
        'N2': [16],
        'S1': [391],
        'S2': [391],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0004': {
        'B': [384],
        'N1': [16],
        'N2': [16],
        'S1': [234],
        'S2': [234],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0005': {
        'B': [352],
        'N1': [16],
        'N2': [16],
        'S1': [234],
        'S2': [234],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0006': {
        'B': [60],
        'N1': [16],
        'N2': [16],
        'S1': [1014],
        'S2': [1014],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0007': {
        'B': [60],
        'N1': [16],
        'N2': [16],
        'S1': [1036],
        'S2': [1036],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0008': {
        'B': [80],
        'N1': [16],
        'N2': [16],
        'S1': [1014],
        'S2': [1014],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0009': {
        'B': [80],
        'N1': [16],
        'N2': [16],
        'S1': [1036],
        'S2': [1036],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0010': {
        'B': [84],
        'N1': [16],
        'N2': [16],
        'S1': [1024],
        'S2': [1024],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0011': {
        'B': [18],
        'N1': [32],
        'N2': [8],
        'S1': [505],
        'S2': [505],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0012': {
        'B': [16],
        'N1': [32],
        'N2': [8],
        'S1': [601],
        'S2': [601],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0013': {
        'B': [15],
        'N1': [32],
        'N2': [8],
        'S1': [755],
        'S2': [755],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0014': {
        'B': [13],
        'N1': [32],
        'N2': [8],
        'S1': [883],
        'S2': [883],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0015': {
        'B': [11],
        'N1': [32],
        'N2': [8],
        'S1': [1100],
        'S2': [1100],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0025': {
        'B': [1],
        'N1': [10],
        'N2': [10],
        'S1': [4000],
        'S2': [512],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0026': {
        'B': [2],
        'N1': [10],
        'N2': [10],
        'S1': [4000],
        'S2': [512],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0027': {
        'B': [1],
        'N1': [10],
        'N2': [10],
        'S1': [4048],
        'S2': [4048],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0028': {
        'B': [2],
        'N1': [10],
        'N2': [10],
        'S1': [4048],
        'S2': [4048],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0029': {
        'B': [4],
        'N1': [10],
        'N2': [10],
        'S1': [4048],
        'S2': [4048],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0030': {
        'B': [4],
        'N1': [10],
        'N2': [10],
        'S1': [4048],
        'S2': [77],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0031': {
        'B': [2],
        'N1': [10],
        'N2': [10],
        'S1': [4048],
        'S2': [512],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0033': {
        'B': [111],
        'N1': [80],
        'N2': [2],
        'S1': [1024],
        'S2': [151],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0038': {
        'B': [10],
        'N1': [23],
        'N2': [1],
        'S1': [144],
        'S2': [99],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0052': {
        'B': [111],
        'N1': [12],
        'N2': [3],
        'S1': [576],
        'S2': [24576],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0056': {
        'B': [16],
        'N1': [12],
        'N2': [1],
        'S1': [576],
        'S2': [8193],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0058': {
        'B': [1],
        'N1': [3],
        'N2': [3],
        'S1': [8192],
        'S2': [8192],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0059': {
        'B': [1],
        'N1': [114],
        'N2': [114],
        'S1': [4096],
        'S2': [4096],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0060': {
        'B': [57],
        'N1': [64],
        'N2': [64],
        'S1': [576],
        'S2': [576],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0061': {
        'B': [4],
        'N1': [104],
        'N2': [104],
        'S1': [128],
        'S2': [128],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0062': {
        'B': [1],
        'N1': [64],
        'N2': [64],
        'S1': [2048],
        'S2': [2048],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0063': {
        'B': [8],
        'N1': [7],
        'N2': [7],
        'S1': [125],
        'S2': [125],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0064': {
        'B': [8],
        'N1': [20],
        'N2': [20],
        'S1': [2286],
        'S2': [2286],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0065': {
        'B': [3],
        'N1': [121],
        'N2': [1],
        'S1': [16],
        'S2': [16],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0067': {
        'B': [144],
        'N1': [4],
        'N2': [1],
        'S1': [52],
        'S2': [9216],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0068': {
        'B': [15],
        'N1': [40],
        'N2': [4],
        'S1': [11],
        'S2': [8192],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0071': {
        'B': [61],
        'N1': [32],
        'N2': [2],
        'S1': [2304],
        'S2': [52],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0072': {
        'B': [32],
        'N1': [7],
        'N2': [1],
        'S1': [4096],
        'S2': [4097],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0073': {
        'B': [3],
        'N1': [48],
        'N2': [24],
        'S1': [4097],
        'S2': [1024],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0074': {
        'B': [6],
        'N1': [24],
        'N2': [12],
        'S1': [8096],
        'S2': [16],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0076': {
        'B': [17],
        'N1': [24],
        'N2': [24],
        'S1': [2304],
        'S2': [16],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0077': {
        'B': [17],
        'N1': [32],
        'N2': [2],
        'S1': [99],
        'S2': [16],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0078': {
        'B': [9],
        'N1': [24],
        'N2': [1],
        'S1': [4096],
        'S2': [576],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0080': {
        'B': [17],
        'N1': [33],
        'N2': [33],
        'S1': [2048],
        'S2': [99],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0082': {
        'B': [24],
        'N1': [10],
        'N2': [10],
        'S1': [2304],
        'S2': [2304],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0083': {
        'B': [24],
        'N1': [20],
        'N2': [20],
        'S1': [576],
        'S2': [576],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0084': {
        'B': [24],
        'N1': [5],
        'N2': [5],
        'S1': [9216],
        'S2': [9216],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
    'flash_atten_test_0085': {
        'B': [32],
        'N1': [33],
        'N2': [33],
        'S1': [8192],
        'S2': [144],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0086': {
        'B': [24],
        'N1': [16],
        'N2': [2],
        'S1': [819],
        'S2': [2304],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0088': {
        'B': [21],
        'N1': [15],
        'N2': [3],
        'S1': [3097],
        'S2': [2304],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0090': {
        'B': [13],
        'N1': [7],
        'N2': [7],
        'S1': [2304],
        'S2': [8096],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['fp16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0091': {
        'B': [16],
        'N1': [33],
        'N2': [1],
        'S1': [8192],
        'S2': [151],
        'D': [128],
        'layout_q': ['BSND'],
        'layout_kv': ['BSND'],
        'layout_out': ['BSND'],
        'Dtype': ['bf16'],
        'mask_mode': [3],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
        'atten_mask_dtype': ['BOOL'],
        'atten_mask_layout': ['SS'],
    },
    'flash_atten_test_0093': {
        'B': [2],
        'N1': [54],
        'N2': [54],
        'S1': [3096],
        'S2': [3096],
        'D': [128],
        'layout_q': ['BNSD'],
        'layout_kv': ['BNSD'],
        'layout_out': ['BNSD'],
        'Dtype': ['bf16'],
        'mask_mode': [0],
        'win_left': [65536],
        'win_right': [65536],
        'q_range': [(-10, 10)],
        'k_range': [(-10, 10)],
        'v_range': [(-10, 10)],
    },
}
