#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# -----------------------------------------------------------------------------------------------------------

import math
import torch


TEST_PARAMS = {
    "bsnd_basic": {
        "Testcase_Prefix": ["sfa_bsnd_basic"],
        "layout_query": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.float16],
        "kv_type": [torch.float16],
        "B": [1],
        "S1": [5],
        "S2": [262144],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [16],
        "scale_value": [1.0 / math.sqrt(576)],
        "sparse_block_size": [1],
        "rope_head_dim": [64],
        "sparse_mode": [0],
        "attention_mode": [2],
        "return_softmax_lse": [True],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[4]],
        "range_query": [[-10.0, 100.0]],
        "range_key": [[5.0, 100.0]],
    },
    "bsnd_multi_batch": {
        "Testcase_Prefix": ["sfa_bsnd_multi_batch"],
        "layout_query": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": [torch.bfloat16],
        "B": [32],
        "S1": [6],
        "S2": [512],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [32],
        "scale_value": [1.0 / math.sqrt(576)],
        "sparse_block_size": [1],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "return_softmax_lse": [True],
        "actual_seq_q": [[2,5,4,2,6,6,0,6,6,2,2,6,3,4,6,4,5,5,6,4,0,4,3,2,3,0,0,3,3,6,2,3]],
        "actual_seq_kv": [[2,5,4,2,6,6,0,6,6,2,2,6,3,4,6,4,5,5,6,4,0,4,3,2,3,0,0,3,3,6,2,3]],
    },
    "pa_bsnd": {
        "Testcase_Prefix": ["sfa_pa_bsnd"],
        "layout_query": ["BSND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.float16],
        "kv_type": [torch.float16],
        "B": [2],
        "S1": [8192],
        "S2": [1024],
        "N1": [16],
        "N2": [1],
        "D": [512],
        "K": [2048],
        "scale_value": [1.0 / math.sqrt(576)],
        "sparse_block_size": [1],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "return_softmax_lse": [False],
        "block_size": [256],
        "block_num": [1051],
        "actual_seq_q": [[18,93]],
        "actual_seq_kv": [[1024,1024]],
    },
    "tnd_basic": {
        "Testcase_Prefix": ["sfa_tnd_basic"],
        "layout_query": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.float16],
        "kv_type": [torch.float16],
        "B": [2],
        "T1": [8],
        "T2": [3072],
        "S1": [4],
        "S2": [3072],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [32],
        "scale_value": [1.0 / math.sqrt(576)],
        "sparse_block_size": [1],
        "rope_head_dim": [64],
        "sparse_mode": [0],
        "attention_mode": [2],
        "return_softmax_lse": [True],
        "actual_seq_q": [[4,8]],
        "actual_seq_kv": [[1111,3000]],
    },
    "tnd_pa_multi_batch": {
        "Testcase_Prefix": ["sfa_tnd_pa_multi_batch"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": [torch.bfloat16],
        "B": [4],
        "T1": [15],
        "S1": [5],
        "S2": [3072],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [64],
        "scale_value": [1.0 / math.sqrt(576)],
        "sparse_block_size": [1],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "return_softmax_lse": [False],
        "block_size": [512],
        "block_num": [74],
        "actual_seq_q": [[2, 6, 11, 15]],
        "actual_seq_kv": [[1024, 1024, 1024, 1024]],
    },
}


ENABLED_PARAMS = [
    TEST_PARAMS["bsnd_basic"],
    TEST_PARAMS["bsnd_multi_batch"],
    TEST_PARAMS["pa_bsnd"], 
    TEST_PARAMS["tnd_basic"],
    TEST_PARAMS["tnd_pa_multi_batch"],
]
