#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

import torch

# 定义测试参数组合
TEST_PARAMS = {
    "swa_decode": {
        "testcase_name": ["swa_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "block_num1": [65],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[8193]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "test_swa_decode_pa": {
        "testcase_name": ["test_swa_decode_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "block_num1": [8],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[1024]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "cfa_tnd": {
        "testcase_name": ["cfa_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "T2": [18],
        "T3": [4],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 18]],
        "cu_seqlens_cmp_kv": [[0, 4]],
        "seqused_cmp_kv": [[4]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_decode":{
        "testcase_name": ["scfa_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "T2": [4],
        "T3": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 4]],
        "cu_seqlens_cmp_kv": [[0, 1]],
        "cmp_residual_kv": [[0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_decode_pa":{
        "testcase_name": ["scfa_decode_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "T2": [1024],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [4],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[1024]],
        "seqused_cmp_kv": [[256]],
        "cmp_residual_kv": [[0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_g128_test_decode":{
        "testcase_name": ["scfa_g128_test_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [1],
        "T1": [2],
        "T2": [2050],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1, 2]],
        "cu_seqlens_ori_kv": [[0, 2050, 4100]],
        "cu_seqlens_cmp_kv": [[0, 512, 1024]],
        "seqused_ori_kv": [[2050, 2050]],
        "seqused_cmp_kv": [[512, 512]],
        "cmp_residual_kv": [[2, 2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_g128_test_decode_B1":{
        "testcase_name": ["scfa_g128_test_decode_B1"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "T1": [1],
        "T2": [2050],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 2050]],
        "cu_seqlens_cmp_kv": [[0, 512]],
        "seqused_ori_kv": [[2050]],
        "seqused_cmp_kv": [[512]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_g128_test_decode_B16": {
        "testcase_name": ["scfa_g128_test_decode_B16"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [16],
        "S1": [1],
        "T1": [16],
        "T2": [128],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]],
        "seqused_ori_kv": [[128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]],
        "seqused_cmp_kv": [[32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]],
        "cmp_residual_kv": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
    },
    "scfa_g64_test_prefill":{
        "testcase_name": ["scfa_g64_test_prefill"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [2],
        "T1": [2],
        "T2": [2050],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512], # cmp_topk
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 2]],
        "cu_seqlens_ori_kv": [[0, 2050]],
        "cu_seqlens_cmp_kv": [[0, 512]],
        "seqused_ori_kv": [[2050]],
        "seqused_cmp_kv": [[512]],
        "cmp_residual_kv": [[2]], # 残差 cmp_residual_kv
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4], # != 1
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3], # == 3
        "ori_win_left": [127],
        "ori_win_right": [0]
    },
    "scfa_g128_test_prefill":{
        "testcase_name": ["scfa_g128_test_prefill"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "T1": [16],
        "T2": [640],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [10],
        "block_num2": [5],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 640]],
        "cu_seqlens_cmp_kv": [[0, 160]],
        "seqused_ori_kv": [[640]],
        "seqused_cmp_kv": [[160]],
        "cmp_residual_kv": [[0]], # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
    },
    "scfa_g128_test_prefill_padding":{
        "testcase_name": ["scfa_g128_test_prefill_padding"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "T1": [16],
        "T2": [38],
        "T3": [9],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 38]],
        "cu_seqlens_cmp_kv": [[0, 9]],
        "seqused_q": [[10]],
        "seqused_ori_kv": [[22]],
        "seqused_cmp_kv": [[5]],
        "cmp_residual_kv": [[2]], # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
    },
    "scfa_g128_test_prefill_TND":{
        "testcase_name": ["scfa_g128_test_prefill_TND"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "S2": [40],
        "T1": [16],
        "T2": [38],
        "T3": [9], # TND且cmp
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 38]],
        "cu_seqlens_cmp_kv": [[0, 9]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
    },
    "cmp_scfa_g64_test_prefill":{
        "testcase_name": ["cmp_scfa_g64_test_prefill"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [38],
        "T1": [38],
        "T2": [166],
        "S2": [166],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "seqused_q": [[38]],
        "seqused_ori_kv": [[166]],
        "seqused_cmp_kv": [[41]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
    }
}

# 按需选择要启用的测试参数（例如默认启用所有）
ENABLED_PARAMS = [{**TEST_PARAMS[key], "testcase_name": [key]} for key in TEST_PARAMS.keys()]
