#!/usr/bin/python3
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""Run fp8 gqa full quant golden cases and print a final pass summary."""

import argparse
import importlib
import json
import os

import result_compare_method


# Load test cases generated by generate_cases.py
_CASES_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cases.json")
with open(_CASES_PATH, "r", encoding="utf-8") as _f:
    CASES = json.load(_f)


def _set_case(module, case):
    module.B = int(case["B"])
    module.N_q = int(case["N_q"])
    module.N_kv = int(case["N_kv"])
    module.D = int(case["D"])
    module.ACTUAL_SEQ_Q = [int(item) for item in case["actual_seq_q"]]
    module.ACTUAL_SEQ_KV = [int(item) for item in case["actual_seq_kv"]]
    module.ENABLE_PA = bool(case.get("enable_pa", module.ENABLE_PA))
    module.ENABLE_LSE = bool(case.get("enable_lse", module.ENABLE_LSE))
    module.GOLDEN_MODE = bool(case.get("golden_mode", True))
    module.BLOCK_SIZE = int(case.get("block_size", module.BLOCK_SIZE))
    module.SPARSE_MODE = int(case.get("sparse_mode", module.SPARSE_MODE))
    module.INPUT_LAYOUT = case.get("input_layout", "NTD_TND")
    module.Q_SCALE_LAYOUT = case.get("q_scale_layout", "NT")
    module.KV_CACHE_LAYOUT = case.get("kv_cache_layout", "BnNBsD")
    module.P_SCALE = float(case["p_scale"])


def run_case(module, case):
    _set_case(module, case)
    try:
        print("=" * 60)
        print(f"  {'PA' if module.ENABLE_PA else ''}  INPUT_LAYOUT={module.INPUT_LAYOUT}  OUTPUT_LAYOUT={'TND' if module.ENABLE_PA else module.INPUT_LAYOUT}")
        print(f"  B={module.B}  N_q={module.N_q}  N_kv={module.N_kv}  D={module.D}  SPARSE_MODE={module.SPARSE_MODE}")
        print(f"  ACTUAL_SEQ_Q={module.ACTUAL_SEQ_Q}")
        print(f"  ACTUAL_SEQ_KV={module.ACTUAL_SEQ_KV}")
        print("=" * 60)

        data = module.generate_data()
        q_fp8, k_fp8, v_fp8, deq_q, deq_k, deq_v, p_scale = data

        if module.GOLDEN_MODE:
            print("[INFO] CPU Running...")
            cpu_out = module.cpu_fp8_fullquant_gqa_golden(
                q_fp8,
                k_fp8,
                v_fp8,
                deq_q,
                deq_k,
                deq_v,
                p_scale,
                module.ACTUAL_SEQ_Q,
                module.ACTUAL_SEQ_KV
            )
            print(f"[INFO] cpu_out[0] shape: {cpu_out[0].shape}, dtype: {cpu_out[0].dtype}")
            if module.ENABLE_LSE:
                print(f"[INFO] cpu_out[1] shape: {cpu_out[1].shape}, dtype: {cpu_out[1].dtype}")
        else:
            print("[INFO] GOLDEN_MODE=False, skip CPU golden.")

        print("[INFO] NPU Running...")
        npu_out = module.npu_fp8_full_quant(
            q_fp8,
            k_fp8,
            v_fp8,
            deq_q,
            deq_k,
            deq_v,
            p_scale,
            module.ACTUAL_SEQ_Q,
            module.ACTUAL_SEQ_KV
        )
        print(f"[INFO] npu_out[0] shape: {npu_out[0].shape}, dtype: {npu_out[0].dtype}")
        if module.ENABLE_LSE:
            print(f"[INFO] npu_out[1] shape: {npu_out[1].shape}, dtype: {npu_out[1].dtype}")

        if not module.GOLDEN_MODE:
            print("[INFO] GOLDEN_MODE=False, skip precision check.")
            return {"name": case["name"], "status": "PASSED", "error_message": ""}

        compare_layout = "TND" if module.ENABLE_PA else module.INPUT_LAYOUT
        cpu_cmp0 = module.convert_q_bnsd_to_layout(cpu_out[0], module.ACTUAL_SEQ_Q, compare_layout)
        print(f"[INFO] cpu_out[0] after convert to {compare_layout}: {cpu_cmp0.shape}")

        print("=" * 80)
        print("  [AttenOut Precision Check]")
        print("=" * 80)
        res0 = result_compare_method.check_result(cpu_cmp0, npu_out[0])
        status0 = res0[0] if isinstance(res0, tuple) else res0

        if module.ENABLE_LSE:
            cpu_cmp1 = module.convert_q_bnsd_to_layout(cpu_out[1], module.ACTUAL_SEQ_Q, compare_layout)
            print("=" * 80)
            print("  [LSE Precision Check]")
            print("=" * 80)
            res1 = result_compare_method.check_result(cpu_cmp1, npu_out[1])
            status1 = res1[0] if isinstance(res1, tuple) else res1
        else:
            status1 = "N/A"
            print("  [LSE] ENABLE_LSE=False, skip LSE precision check.")

        if status0 != "Pass" or (status1 != "Pass" and status1 != "N/A"):
            err_msg = f"AttenOut={status0}, LSE={status1}"
            return {"name": case["name"], "status": "FAILED", "error_message": err_msg}
        return {"name": case["name"], "status": "PASSED", "error_message": ""}
    except Exception as exc:
        return {"name": case["name"], "status": "FAILED", "error_message": f"{type(exc).__name__}: {exc}"}


def main():
    parser = argparse.ArgumentParser(description="Run FP8 Full Quant batch cases")
    parser.add_argument("--case", action="append", default=None, help="Run only matching case name substring")
    args = parser.parse_args()

    module = importlib.import_module("fia_fullquant_gqa_golden")
    selected = CASES
    if args.case:
        selected = [case for case in CASES if any(item in case["name"] for item in args.case)]
    if not selected:
        raise ValueError("No cases selected")

    results = []
    total = len(selected)
    for idx, case in enumerate(selected, 1):
        print(f"\n[CASE] [{idx}/{total}] {case['name']}")
        result = run_case(module, case)
        results.append(result)
        if result["status"] == "FAILED":
            print(f"  [FAILED] {result['error_message']}")

    passed = sum(item["status"] == "PASSED" for item in results)
    print("\n[SUMMARY]")
    print(f"{'case':<48} {'status':<8} error_message")
    for item in results:
        print(f"{item['name']:<48} {item['status']:<8} {item['error_message']}")
    print(f"[SUMMARY] TOTAL {passed}/{len(results)} PASSED")


if __name__ == "__main__":
    main()
