#!/usr/bin/python3
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

from fia_fullquant_mxfp8_paramset_common import expand_paramset_to_cases

TEST_PARAMS = {
    "PA_BnNBsD_B1_QS0_KVS64_Nq1_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[0]],
        'actual_seq_kv': [[64]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS7_KVS1555_Nq1_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[7]],
        'actual_seq_kv': [[1555]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3_KVS640_Nq1_Nkv1_D64_SP0": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[640]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B8_QS60_KVS1536_Nq4_Nkv4_D128_SP3": {
        'B': [8],
        'N_q': [4],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[60, 64, 64, 64, 64, 64, 61, 64]],
        'actual_seq_kv': [[128, 0, 64, 0, 256, 512, 192, 384]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_NZ_B3_QS1_KVS192_Nq16_Nkv1_D128_SP3": {
        'B': [3],
        'N_q': [16],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1, 1, 64]],
        'actual_seq_kv': [[0, 64, 128]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS15_KVS0_Nq20_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [20],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[15]],
        'actual_seq_kv': [[0]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3000_KVS6000_Nq16_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[3000]],
        'actual_seq_kv': [[6000]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS3_KVS3584_Nq8_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[3584]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B6_QS700_KVS4800_Nq64_Nkv1_D128_SP3": {
        'B': [6],
        'N_q': [64],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[700, 448, 640, 448, 512, 896]],
        'actual_seq_kv': [[4800, 4963, 4224, 3350, 4606, 5120]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS5_KVS3072_Nq32_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [32],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[3072]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS384_KVS256_Nq48_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[384]],
        'actual_seq_kv': [[256]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS1_KVS500_Nq40_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [40],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS512_KVS5120_Nq80_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [80],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[512]],
        'actual_seq_kv': [[5120]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B3_QS4_KVS3072_Nq1_Nkv1_D128_SP3": {
        'B': [3],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1, 0, 3]],
        'actual_seq_kv': [[3072, 3328, 3827]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS1100_KVS7000_Nq20_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1100]],
        'actual_seq_kv': [[7000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS1800_KVS1500_Nq128_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [128],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1800]],
        'actual_seq_kv': [[1500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "TND_B1_QS600_KVS500_Nq16_Nkv8_D128_SP0": {
        'B': [1],
        'N_q': [16],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[600]],
        'actual_seq_kv': [[500]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS3_KVS896_Nq224_Nkv16_D128_SP3": {
        'B': [1],
        'N_q': [224],
        'N_kv': [16],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[896]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS2048_KVS1024_Nq40_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [40],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[2048]],
        'actual_seq_kv': [[1024]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS128_KVS4500_Nq128_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [128],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[128]],
        'actual_seq_kv': [[4500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B6_QS2000_KVS2111_Nq128_Nkv4_D128_SP0": {
        'B': [6],
        'N_q': [128],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[2000, 2641, 2555, 2329, 2176, 1399]],
        'actual_seq_kv': [[2111, 2688, 1577, 2752, 2048, 2209]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1500_KVS77_Nq80_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [80],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1500]],
        'actual_seq_kv': [[77]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B5_QS3_KVS7000_Nq32_Nkv8_D128_SP0": {
        'B': [5],
        'N_q': [32],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[3, 64, 4, 64, 2]],
        'actual_seq_kv': [[7000, 7616, 7549, 7990, 5156]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B1_QS10_KVS128_Nq2_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[10]],
        'actual_seq_kv': [[128]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B3_QS1_KVS999_Nq256_Nkv4_D64_SP3": {
        'B': [3],
        'N_q': [256],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[1, 1, 2]],
        'actual_seq_kv': [[999, 1216, 832]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B5_QS1_KVS5504_Nq48_Nkv1_D64_SP3": {
        'B': [5],
        'N_q': [48],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[1, 64, 64, 64, 64]],
        'actual_seq_kv': [[5504, 5111, 5448, 3648, 3926]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B7_QS455_KVS2048_Nq8_Nkv1_D128_SP3": {
        'B': [7],
        'N_q': [8],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[455, 320, 308, 448, 448, 448, 512]],
        'actual_seq_kv': [[2048, 2496, 2048, 2668, 2176, 1600, 1847]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS10_KVS4096_Nq48_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[10]],
        'actual_seq_kv': [[4096]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS699_KVS555_Nq8_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[699]],
        'actual_seq_kv': [[555]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B4_QS700_KVS3584_Nq1_Nkv1_D128_SP3": {
        'B': [4],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[700, 889, 496, 665]],
        'actual_seq_kv': [[3584, 2988, 3582, 3968]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS333_KVS1555_Nq48_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[333]],
        'actual_seq_kv': [[1555]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS100_KVS5500_Nq16_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[100]],
        'actual_seq_kv': [[5500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1500_KVS4200_Nq48_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[1500]],
        'actual_seq_kv': [[4200]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_NZ_B6_QS211_KVS900_Nq64_Nkv1_D128_SP0": {
        'B': [6],
        'N_q': [64],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[211, 277, 256, 183, 192, 128]],
        'actual_seq_kv': [[900, 576, 1024, 576, 932, 1127]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1088_KVS2500_Nq20_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[1088]],
        'actual_seq_kv': [[2500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS15_KVS5500_Nq16_Nkv4_D64_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[15]],
        'actual_seq_kv': [[5500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B1_QS699_KVS777_Nq64_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [64],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[699]],
        'actual_seq_kv': [[777]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B8_QS1_KVS999_Nq128_Nkv4_D128_SP3": {
        'B': [8],
        'N_q': [128],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1, 1, 2, 1, 64, 64, 64, 1]],
        'actual_seq_kv': [[999, 748, 1152, 640, 1216, 1280, 1015, 802]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1024_KVS2048_Nq224_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [224],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[1024]],
        'actual_seq_kv': [[2048]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B5_QS1_KVS7040_Nq40_Nkv8_D128_SP3": {
        'B': [5],
        'N_q': [40],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1, 64, 64, 1, 1]],
        'actual_seq_kv': [[7040, 8128, 6530, 5727, 4742]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B5_QS1100_KVS8000_Nq2_Nkv1_D128_SP3": {
        'B': [5],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1100, 1349, 1216, 1280, 768]],
        'actual_seq_kv': [[8000, 8128, 8128, 7108, 8144]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS1_KVS8000_Nq128_Nkv4_D64_SP0": {
        'B': [1],
        'N_q': [128],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[8000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B4_QS2_KVS1536_Nq80_Nkv2_D128_SP0": {
        'B': [4],
        'N_q': [80],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[2, 1, 64, 1]],
        'actual_seq_kv': [[1536, 1792, 1382, 1792]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B6_QS1_KVS333_Nq48_Nkv8_D128_SP3": {
        'B': [6],
        'N_q': [48],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1, 64, 1, 64, 64, 64]],
        'actual_seq_kv': [[333, 341, 384, 384, 384, 320]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS5_KVS640_Nq1_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[640]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B2_QS900_KVS1500_Nq96_Nkv16_D128_SP3": {
        'B': [2],
        'N_q': [96],
        'N_kv': [16],
        'D': [128],
        'actual_seq_q': [[900, 1066]],
        'actual_seq_kv': [[1500, 1927]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS704_KVS320_Nq128_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [128],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[704]],
        'actual_seq_kv': [[320]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B5_QS2_KVS128_Nq16_Nkv4_D128_SP3": {
        'B': [5],
        'N_q': [16],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[2, 2, 64, 2, 64]],
        'actual_seq_kv': [[128, 128, 128, 133, 114]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS700_KVS4480_Nq40_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [40],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[700]],
        'actual_seq_kv': [[4480]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B6_QS704_KVS700_Nq2_Nkv2_D128_SP3": {
        'B': [6],
        'N_q': [2],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[704, 448, 930, 777, 617, 931]],
        'actual_seq_kv': [[700, 631, 583, 499, 576, 640]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS3_KVS384_Nq192_Nkv8_D128_SP0": {
        'B': [1],
        'N_q': [192],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[384]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS768_KVS5504_Nq56_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [56],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[768]],
        'actual_seq_kv': [[5504]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS1500_KVS5000_Nq160_Nkv8_D128_SP0": {
        'B': [1],
        'N_q': [160],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1500]],
        'actual_seq_kv': [[5000]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS1500_KVS1500_Nq256_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [256],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1500]],
        'actual_seq_kv': [[1500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS704_KVS555_Nq1_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[704]],
        'actual_seq_kv': [[555]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS11_KVS2560_Nq1_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[11]],
        'actual_seq_kv': [[2560]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS512_KVS6500_Nq1_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[512]],
        'actual_seq_kv': [[6500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS5_KVS6000_Nq128_Nkv16_D128_SP0": {
        'B': [1],
        'N_q': [128],
        'N_kv': [16],
        'D': [128],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[6000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1152_KVS900_Nq48_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[1152]],
        'actual_seq_kv': [[900]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS1_KVS7040_Nq64_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[7040]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS3500_KVS3500_Nq20_Nkv4_D64_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[3500]],
        'actual_seq_kv': [[3500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS1_KVS1100_Nq32_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [32],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[1100]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS800_KVS3333_Nq4_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[800]],
        'actual_seq_kv': [[3333]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS15_KVS5000_Nq16_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[15]],
        'actual_seq_kv': [[5000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B4_QS211_KVS320_Nq48_Nkv2_D64_SP3": {
        'B': [4],
        'N_q': [48],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[211, 152, 268, 128]],
        'actual_seq_kv': [[320, 320, 402, 256]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B5_QS41_KVS4096_Nq1_Nkv1_D128_SP3": {
        'B': [5],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[41, 64, 64, 42, 64]],
        'actual_seq_kv': [[4096, 3530, 3008, 4288, 4544]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B1_QS3_KVS768_Nq16_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[768]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS150_KVS3072_Nq2_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[150]],
        'actual_seq_kv': [[3072]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B2_QS100_KVS320_Nq224_Nkv4_D128_SP3": {
        'B': [2],
        'N_q': [224],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[100, 122]],
        'actual_seq_kv': [[320, 325]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS455_KVS3584_Nq56_Nkv2_D64_SP0": {
        'B': [1],
        'N_q': [56],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[455]],
        'actual_seq_kv': [[3584]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS2_KVS192_Nq1_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[2]],
        'actual_seq_kv': [[192]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS60_KVS500_Nq64_Nkv64_D64_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [64],
        'D': [64],
        'actual_seq_q': [[60]],
        'actual_seq_kv': [[500]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS211_KVS100_Nq16_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [16],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[211]],
        'actual_seq_kv': [[100]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS2_KVS640_Nq56_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [56],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[2]],
        'actual_seq_kv': [[640]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS2000_KVS320_Nq4_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [4],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[2000]],
        'actual_seq_kv': [[320]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B6_QS4000_KVS512_Nq8_Nkv8_D128_SP3": {
        'B': [6],
        'N_q': [8],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[4000, 3264, 3463, 3655, 3668, 2944]],
        'actual_seq_kv': [[512, 320, 640, 320, 468, 565]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS3_KVS256_Nq64_Nkv4_D64_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[256]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS700_KVS2111_Nq8_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[700]],
        'actual_seq_kv': [[2111]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B3_QS933_KVS3584_Nq96_Nkv2_D128_SP3": {
        'B': [3],
        'N_q': [96],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[933, 768, 911]],
        'actual_seq_kv': [[3584, 3712, 2496]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B1_QS10_KVS1536_Nq8_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[10]],
        'actual_seq_kv': [[1536]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS50_KVS6500_Nq1_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[50]],
        'actual_seq_kv': [[6500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B1_QS4032_KVS2048_Nq8_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[4032]],
        'actual_seq_kv': [[2048]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1800_KVS2048_Nq20_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1800]],
        'actual_seq_kv': [[2048]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS1_KVS3072_Nq160_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [160],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[3072]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS2048_KVS3584_Nq8_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[2048]],
        'actual_seq_kv': [[3584]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS3_KVS320_Nq128_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [128],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[320]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS3000_KVS1100_Nq56_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [56],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[3000]],
        'actual_seq_kv': [[1100]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS7_KVS777_Nq56_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [56],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[7]],
        'actual_seq_kv': [[777]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1_KVS999_Nq80_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [80],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[999]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS2_KVS6500_Nq96_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [96],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[2]],
        'actual_seq_kv': [[6500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B1_QS2048_KVS77_Nq32_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [32],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[2048]],
        'actual_seq_kv': [[77]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS33_KVS6500_Nq8_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[33]],
        'actual_seq_kv': [[6500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS1500_KVS2111_Nq32_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [32],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1500]],
        'actual_seq_kv': [[2111]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS5_KVS4480_Nq40_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [40],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[4480]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B4_QS1500_KVS1500_Nq1_Nkv1_D128_SP3": {
        'B': [4],
        'N_q': [1],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1500, 1792, 1216, 1522]],
        'actual_seq_kv': [[1500, 1408, 1152, 1920]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS4000_KVS896_Nq8_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [8],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[4000]],
        'actual_seq_kv': [[896]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS3584_KVS192_Nq128_Nkv4_D64_SP0": {
        'B': [1],
        'N_q': [128],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[3584]],
        'actual_seq_kv': [[192]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [128.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "TND_B1_QS333_KVS5504_Nq20_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [20],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[333]],
        'actual_seq_kv': [[5504]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS15_KVS700_Nq4_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[15]],
        'actual_seq_kv': [[700]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B4_QS5_KVS640_Nq2_Nkv1_D128_SP3": {
        'B': [4],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[5, 64, 5, 64]],
        'actual_seq_kv': [[640, 662, 607, 384]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS128_KVS1536_Nq4_Nkv4_D128_SP0": {
        'B': [1],
        'N_q': [4],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[128]],
        'actual_seq_kv': [[1536]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS1024_KVS6000_Nq64_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[1024]],
        'actual_seq_kv': [[6000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS832_KVS4500_Nq128_Nkv8_D128_SP0": {
        'B': [1],
        'N_q': [128],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[832]],
        'actual_seq_kv': [[4500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3_KVS192_Nq2_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[192]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS800_KVS2000_Nq4_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[800]],
        'actual_seq_kv': [[2000]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B4_QS2_KVS4500_Nq56_Nkv2_D64_SP3": {
        'B': [4],
        'N_q': [56],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[2, 64, 64, 64]],
        'actual_seq_kv': [[4500, 3388, 4330, 5696]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS384_KVS128_Nq20_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[384]],
        'actual_seq_kv': [[128]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B5_QS2560_KVS5500_Nq96_Nkv8_D128_SP3": {
        'B': [5],
        'N_q': [96],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[2560, 2432, 1965, 1994, 1664]],
        'actual_seq_kv': [[5500, 6912, 3776, 4544, 4489]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3_KVS640_Nq40_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [40],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[640]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS1200_KVS6500_Nq16_Nkv4_D64_SP0": {
        'B': [1],
        'N_q': [16],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[1200]],
        'actual_seq_kv': [[6500]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B3_QS4000_KVS3000_Nq80_Nkv4_D64_SP3": {
        'B': [3],
        'N_q': [80],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[4000, 2880, 3072]],
        'actual_seq_kv': [[3000, 2176, 2048]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B4_QS5_KVS3500_Nq4_Nkv1_D128_SP3": {
        'B': [4],
        'N_q': [4],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[5, 4, 4, 5]],
        'actual_seq_kv': [[3500, 2700, 3520, 3968]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS5_KVS900_Nq56_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [56],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[900]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "TND_B4_QS1_KVS6500_Nq8_Nkv2_D128_SP3": {
        'B': [4],
        'N_q': [8],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1, 1, 1, 1]],
        'actual_seq_kv': [[6500, 6656, 4340, 6490]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B4_QS150_KVS200_Nq64_Nkv2_D64_SP3": {
        'B': [4],
        'N_q': [64],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[150, 128, 128, 153]],
        'actual_seq_kv': [[200, 192, 134, 263]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B5_QS60_KVS192_Nq8_Nkv8_D128_SP3": {
        'B': [5],
        'N_q': [8],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[60, 64, 51, 68, 78]],
        'actual_seq_kv': [[192, 128, 128, 192, 192]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1100_KVS4500_Nq2_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [2],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1100]],
        'actual_seq_kv': [[4500]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B7_QS65_KVS1555_Nq1_Nkv1_D64_SP3": {
        'B': [7],
        'N_q': [1],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[65, 79, 64, 60, 84, 64, 64]],
        'actual_seq_kv': [[1555, 1216, 1152, 1536, 1536, 1569, 1281]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B3_QS455_KVS7000_Nq16_Nkv1_D128_SP3": {
        'B': [3],
        'N_q': [16],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[455, 365, 448]],
        'actual_seq_kv': [[7000, 7168, 6528]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1_KVS333_Nq32_Nkv1_D128_SP0": {
        'B': [1],
        'N_q': [32],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[333]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS1_KVS896_Nq48_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[896]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1_KVS640_Nq32_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [32],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[640]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B1_QS704_KVS900_Nq32_Nkv32_D128_SP0": {
        'B': [1],
        'N_q': [32],
        'N_kv': [32],
        'D': [128],
        'actual_seq_q': [[704]],
        'actual_seq_kv': [[900]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B1_QS3000_KVS3072_Nq256_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [256],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[3000]],
        'actual_seq_kv': [[3072]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3_KVS768_Nq160_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [160],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[768]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1_KVS5120_Nq128_Nkv8_D128_SP3": {
        'B': [1],
        'N_q': [128],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[5120]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1_KVS256_Nq64_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[256]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS7_KVS512_Nq2_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [2],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[7]],
        'actual_seq_kv': [[512]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B3_QS1_KVS128_Nq128_Nkv2_D128_SP3": {
        'B': [3],
        'N_q': [128],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1, 1, 1]],
        'actual_seq_kv': [[128, 131, 109]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B1_QS30_KVS5120_Nq32_Nkv32_D128_SP3": {
        'B': [1],
        'N_q': [32],
        'N_kv': [32],
        'D': [128],
        'actual_seq_q': [[30]],
        'actual_seq_kv': [[5120]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B8_QS1536_KVS100_Nq32_Nkv4_D64_SP0": {
        'B': [8],
        'N_q': [32],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[1536, 1280, 1856, 1032, 1289, 1152, 1536, 1822]],
        'actual_seq_kv': [[100, 75, 82, 64, 73, 91, 106, 110]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS133_KVS512_Nq4_Nkv4_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [4],
        'D': [128],
        'actual_seq_q': [[133]],
        'actual_seq_kv': [[512]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [128.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS900_KVS333_Nq2_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [2],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[900]],
        'actual_seq_kv': [[333]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B3_QS1_KVS6528_Nq96_Nkv8_D128_SP3": {
        'B': [3],
        'N_q': [96],
        'N_kv': [8],
        'D': [128],
        'actual_seq_q': [[1, 64, 1]],
        'actual_seq_kv': [[6528, 5952, 8128]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS13_KVS1555_Nq1_Nkv1_D64_SP3": {
        'B': [1],
        'N_q': [1],
        'N_kv': [1],
        'D': [64],
        'actual_seq_q': [[13]],
        'actual_seq_kv': [[1555]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS3000_KVS2500_Nq48_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [48],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[3000]],
        'actual_seq_kv': [[2500]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B8_QS1536_KVS768_Nq20_Nkv4_D64_SP3": {
        'B': [8],
        'N_q': [20],
        'N_kv': [4],
        'D': [64],
        'actual_seq_q': [[1536, 1158, 1280, 1120, 1152, 1408, 1912, 1728]],
        'actual_seq_kv': [[768, 704, 555, 830, 725, 671, 612, 563]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B8_QS1_KVS3000_Nq64_Nkv1_D128_SP3": {
        'B': [8],
        'N_q': [64],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[1, 2, 64, 64, 64, 1, 64, 64]],
        'actual_seq_kv': [[3000, 3644, 3601, 3136, 3008, 2496, 3712, 3083]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B1_QS500_KVS192_Nq20_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [20],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[500]],
        'actual_seq_kv': [[192]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [256.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "TND_B3_QS100_KVS6000_Nq48_Nkv2_D64_SP0": {
        'B': [3],
        'N_q': [48],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[100, 78, 67]],
        'actual_seq_kv': [[6000, 6473, 6128]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [512],
        'sparse_mode': [0],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_BnNBsD_B1_QS1088_KVS192_Nq4_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1088]],
        'actual_seq_kv': [[192]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [True],
    },
    "PA_NZ_B1_QS5_KVS192_Nq16_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [16],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[5]],
        'actual_seq_kv': [[192]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "PA_NZ_B6_QS576_KVS1024_Nq8_Nkv2_D128_SP3": {
        'B': [6],
        'N_q': [8],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[576, 723, 616, 510, 640, 512]],
        'actual_seq_kv': [[1024, 1152, 974, 1259, 1350, 1024]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS15_KVS100_Nq4_Nkv1_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [1],
        'D': [128],
        'actual_seq_q': [[15]],
        'actual_seq_kv': [[100]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS20_KVS2048_Nq4_Nkv2_D128_SP3": {
        'B': [1],
        'N_q': [4],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[20]],
        'actual_seq_kv': [[2048]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_NZ_B1_QS3_KVS7000_Nq64_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [64],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[3]],
        'actual_seq_kv': [[7000]],
        'enable_pa': [True],
        'kv_cache_layout': ['PA_NZ'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "TND_B5_QS1_KVS448_Nq64_Nkv2_D128_SP3": {
        'B': [5],
        'N_q': [64],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[1, 64, 64, 1, 64]],
        'actual_seq_kv': [[128, 64, 256, 0, 0]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [3],
        'q_scale_layout': ['TND'],
        'p_scale': [1.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS7_KVS2000_Nq8_Nkv8_D64_SP3": {
        'B': [1],
        'N_q': [8],
        'N_kv': [8],
        'D': [64],
        'actual_seq_q': [[7]],
        'actual_seq_kv': [[2000]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [1.0],
        'enable_lse': [False],
        'enable_rope': [True],
    },
    "TND_B1_QS70_KVS640_Nq2_Nkv2_D128_SP0": {
        'B': [1],
        'N_q': [2],
        'N_kv': [2],
        'D': [128],
        'actual_seq_q': [[70]],
        'actual_seq_kv': [[640]],
        'enable_pa': [False],
        'kv_cache_layout': ['TND'],
        'block_size': [1024],
        'sparse_mode': [0],
        'q_scale_layout': ['TND'],
        'p_scale': [100.0],
        'enable_lse': [False],
        'enable_rope': [False],
    },
    "PA_BnNBsD_B1_QS1_KVS64_Nq128_Nkv2_D64_SP3": {
        'B': [1],
        'N_q': [128],
        'N_kv': [2],
        'D': [64],
        'actual_seq_q': [[1]],
        'actual_seq_kv': [[64]],
        'enable_pa': [True],
        'kv_cache_layout': ['BnNBsD'],
        'block_size': [512],
        'sparse_mode': [3],
        'q_scale_layout': ['N2TGD'],
        'p_scale': [15.0],
        'enable_lse': [True],
        'enable_rope': [False],
    },
}

SKIP_CASES = {
    "PA_NZ_B8_QS60_KVS1536_Nq4_Nkv4_D128_SP3",
    "PA_NZ_B8_QS1_KVS999_Nq128_Nkv4_D128_SP3"
}

CASES = expand_paramset_to_cases(TEST_PARAMS)
